public enum FurnitureType
{
	NONE = -1,
	OVEN,
	CHECKOUT_DESK,
	SELF_CHECKOUT,
	PALLET_RACK,
	TRAY_STATION,
	FITTING_ROOM,
	MANNEQUIN_SPORT,
	TRASH_FURNITURE,
	RECYCLE_BIN,
	BOX_SHELF,
	BOX_SHELF_SMALL,
	WALK_IN_FREEZER_SMALL,
	WALK_IN_FREEZER_MEDIUM,
	WALK_IN_FREEZER_LARGE,
	SMALL_PALLET_RACK,
	INFLATABLE_POOL,
	COUNT
}
