public static class ProductEvents
{
	public static string INITIAL_LICENSE_DECIDED = "INITIAL_LICENSE_DECIDED";

	public static string PRODUCT_PRICE_CHANGED = "PRICE_CHANGED";

	public static string PRODUCT_ADDEDTO_CART = "PRODUCT_ADDEDTO_CART";

	public static string PRODUCT_REMOVEDFROM_CART = "PRODUCT_REMOVEDFROM_CART";

	public static string PALLET_STATUS_CHANGED = "PALLET_STATUS_CHANGED";

	public static string MULTIPLE_PRODUCTS_ADDED_TO_CART = "MULTIPLE_PRODUCTS_ADDED_TO_CART";

	public static string PRODUCT_LICENSE_PURCHASED = "PRODUCT_LICENSE_PURCHASED";

	public static string PRODUCT_DELETED_FROM_CART = "PRODUCT_DELETED_FROM_CART";

	public static string SCANNER_PRODUCT_ADDEDTO_CART_BOX_SHELF = "SCANNER_PRODUCT_ADDEDTO_CART_BOX_SHELF";

	public static string SCANNER_PRODUCT_ADDEDTO_CART = "SCANNER_PRODUCT_ADDEDTO_CART";

	public static string SCANNER_PRODUCT_REMOVEDFROM_CART = "SCANNER_PRODUCT_REMOVEDFROM_CART";

	public static string SCANNER_PRODUCT_REMOVEDFROM_CART_BOX_SHELF = "SCANNER_PRODUCT_REMOVEDFROM_CART_BOX_SHELF";

	public static string PRICE_TAG_HOVER_STARTED = "PRICE_TAG_HOVER_STARTED";
}
