public enum TutorialVideoWindowType
{
	PALLET_DISPOSAL,
	VENDING_COLLECT_MONEY,
	HANDTRUCK_TUTORIAL,
	BAKER_TUTORIAL,
	RESTOCKER_TUTORIAL,
	UNLOADER_TUTORIAL,
	SEAFOOD_STAFF_TUTORIAL,
	FISH_STAND_TUTORIAL,
	WALKIN_FREEZER_TUTORIAL
}
