public static class UIEvents
{
	public static string CART_WINDOW_OPENED = "CART_WINDOW_OPENED";

	public static string SHOP_WINDOW_OPENED = "SHOP_WINDOW_OPENED";

	public static string ROTATION_MULTIPLIER_CHANGED = "ROTATION_MULTIPLIER_CHANGED";

	public static string FIELD_OF_VIEW_CHANGED = "FIELD_OF_VIEW_CHANGED";

	public static string OPEN_INCOME_OFFER = "OPEN_INCOME_OFFER";

	public static string INTERACTION_CLICKED = "INTERACTION_CLICKED";

	public static string UI_WINDOW_CLOSED = "UI_WINDOW_CLOSED";

	public static string SETTING_WINDOW_CLOSED = "SETTING_WINDOW_CLOSED";

	public static string AUDIO_MULTIPLIER_CHANGED = "AUDIO_MULTIPLIER_CHANGED";

	public static string DIALOGUE_MULTIPLIER_CHANGED = "DIALOGUE_MULTIPLIER_CHANGED";

	public static string OPEN_EMPLOYEE_FIRE_POPUP = "OPEN_EMPLOYEE_FIRE_POPUP";

	public static string PRODUCT_DRAW_DISTANCE_CHANGED = "PRODUCT_DRAW_DISTANCE_CHANGED";

	public static string UI_WINDOW_PUSHED = "UI_WINDOW_PUSHED";

	public static string UI_WINDOW_POPPED = "UI_WINDOW_POPPED";

	public static string INPUT_DEVICE_CHANGED = "INPUT_DEVICE_CHANGED";

	public static string TAB_SELECTED_OBJECT_CHANGED = "TAB_SELECTED_OBJECT_CHANGED";

	public static string EMPLOYEE_PAUSE_CLICKED = "EMPLOYEE_PAUSE_CLICKED";

	public static string LEAVE_TRIGGERED = "LEAVE_TRIGGERED";

	public static string FAKE_LOADING_FINISHED = "FAKE_LOADING_FINISHED";

	public static string OPEN_PRODUCT_SALES_GRAPH = "OPEN_PRODUCT_SALES_GRAPH";

	public static string CLOSE_PRODUCT_SALES_GRAPH = "CLOSE_PRODUCT_SALES_GRAPH";
}
